{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actual-budget.fullname" . }}-data
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.keepPvc }}
    "helm.sh/resource-policy": keep
  {{- end }}
  {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | required "storage size is mandatory" }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}